name: EAS Build
on:
  release:
    types: [created]
jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Setup Expo
        uses: expo/expo-github-action@v6
        with:
          expo-version: 4.x
          expo-token: ${{ secrets.EXPO_TOKEN }}
          expo-cache: true
      - name: Install Prod dependencies
        run: npm ci --only=production
      - name: Build on EAS
        run: npx eas-cli build --platform all --non-interactive